### PR TITLE
Reptiles Mod Support

### PR DESCRIPTION
**Pull request by Sunconure11**
Due to discontinuation of 1.10.2 and 1.11.2 versions, barring bugs, and the fact that this feature is only on newer versions of the reptiles mod, I am adding it to the 1.12 branch.

### CODE REVIEW

**Comment by WesCook** [comment]
Thanks!  I've just released as part of [v2.1.0](https://github.com/WesCook/Nutrition/releases/tag/v2.1.0).

So you know, we lost a number of mods making the jump to 1.12.  However as they're updated it should be pretty easy to copy their entries over as well.

**Comment by Sunconure11** [comment]
@WesCook I think Animania might be working on a major update for 1.11.2, they're overhauling rabbits, sheep, and adding goats, it would seem. In the event they push out that update on 1.11.2, would you be fine with me pushing out a config to update Animania support on 1.11.2 until they move to 1.12? They're dependency-bound too, so they have reason to stay on 1.11.2 until their dependency ports.

**Comment by WesCook** [comment]
I've given this some thought.  I'm sorry to say but I've decided not to continue supporting previous versions at this time.

I understand your perspective that because Animania hasn't made the jump to 1.12 yet, it should still be supported.  And I do partially agree.  My concern though is that if I start making exceptions, I may indefinitely need to be supporting older versions as modders are resistant to update, or simply cannot update due to reasons beyond their control.

As a modpack author, I also noticed that 1.10 and 1.11 updates have significantly dried up since 1.12 became commonplace.  I took this as a sign that it was okay to move beyond those previous versions.

During development, I also used this opportunity to make some technical changes to the codebase which do not exist in the 1.10 and 1.11 branches.  This could make maintaining multiple versions more difficult.

All that said, Nutrition is designed to be flexible even without me baking mod support into the source.  It's very possible for pack authors to create their own configs with Animania, or distribute it for others.  So I do feel less obligated to continue supporting these older versions as a consequence of this.

Admittedly there's not a centralized place for pack authors to share configs.  My suggestion would be to create a Github issue to share pack configs for older versions though.  Or, if the config is for a completely different food group system, that would be an acceptable place as well.

I wouldn't want to keep these issues "Open", but I could create a unique tag to make them searchable.

Hopefully that's a reaonsable position.  You've submitted the most PRs though, so I'd be curious to know your thoughts.

**Comment by Sunconure11** [comment]
Why not use a wiki page for this, and players could submit their configs through either an issue you set up, or through editing the wiki page (in the case of editing the wiki page, users should place the date they added the configs, and their GitHub username)

**Comment by WesCook** [comment]
Fair point.  If I receive a number of submissions for older or alternative configs, I'll make a wiki page for it and set up a proper system.  Until then though, I'm going to keep it simple and suggest sharing via an issue.

**Comment by Sunconure11** [comment]
@WesCook Looks like all of those teasers in the Animania discord channel were right. I'll just see about creating a config with any new items for 1.11.2 and 1.10.2 when it releases, unless an exception is made.

https://twitter.com/Purplicious_Cow/status/894321194878595073

**Pull request merged**
