### PR TITLE
Some tweaks to plants support, plus updates to betweenlands support, and the start of erebus support

### PR DESCRIPTION
**Pull request by Sunconure11**
Some of these are fruits rather than veggies. Either that, or things screwed up

Pretty sure [wine raspberries](https://en.wikipedia.org/wiki/Rubus_phoenicolasius) are fruit

Also updated Betweenlands supported, and added Erebus support.

### CODE REVIEW

**Comment by Sunconure11** [comment]
Erebus is out, but I'll wait to add support for it, I'm currently having an issue with it crashing with what I'm pretty sure is BoP.

**Comment by Sunconure11** [comment]
Hopefully these conflicts are resolved...

**Comment by WesCook** [comment]
I merged the other first as it was relatively simple (only one mod), so should be easier to add to this one.  I'm also not sure if this one is finished or not (again, "Start of..." in title).

Thanks for handling the conflict.

**Comment by Sunconure11** [comment]
It's finished, as there are some things I was unable to decide on food groups, combined with some stuttering I've been running into that's been making playing MC in singleplayer for testing a bit difficult.

**Comment by WesCook** [comment]
Great, thanks again.  I'll go ahead and merge this now then.

Stuttering (or lag spikes) are often related to Java garbage collection.  You might try double checking your ram allocation, or installing Foamfix for additional memory reduction.

**Comment by Sunconure11** [comment]
I have 8 gigs allocated, and foamfix installed. If you think you can think of a better set of arguments for garbage collection, here are my args:

`-Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UseG1GC -XX:G1ReservePercent=50 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
`

**Comment by WesCook** [comment]
With the exception of specifying the garbage collector (G1), most args are unfortunately just placebo.  cpw posted a recommendation on the FTB sub that is probably your best bet though.

https://www.reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/

**Comment by WesCook** [comment]
These changes are included in [v2.9.0](https://github.com/WesCook/Nutrition/releases/tag/v2.9.0).

**Pull request merged**
