### PR TITLE
Grab bag of mod support

### PR DESCRIPTION
**Pull request by Sunconure11**

### CODE REVIEW

**Comment by Sunconure11** [comment]
Should be mostly done @WesCook, though I do want to update Tropicraft support since it added meats for various tropical fish

**Comment by WesCook** [comment]
Thanks!  Let me know when it's ready for merge.

**Comment by Sunconure11** [comment]
It should be ready for merge.

Artifacts and Xeno's Reliquary also have some things I'd like to add support for later, or see support added for, at least.

**Comment by WesCook** [comment]
I generally don't add support for mods if they only have one or two foods because it makes maintaining them a lot harder.  eg. adding EnderIO to the dev environment really slows things down, and it only adds one food item.

I'd just ask you consider that before adding support for those types of mods.  Though I'm not sure if Reliquary/Artifacts meet that description or not.

**Comment by Sunconure11** [comment]
Artifacts has more than one food item

**Pull request merged**
