### PR TITLE
 Heat and Climate support

### PR DESCRIPTION
**Pull request by ghost**
Hopefully this is all the food items in heat and climate, would love it if someone could double check my work because there were quite a few food to get through.

### CODE REVIEW

**Comment by WesCook** [comment]
Edits look good to me, thanks.  I can merge and test those out shortly.

In the mean time, could you tell me a little bit about the mod?  It's one I'm not familiar with.  Thank you!

**Comment by ghost** [comment]
Its by the guy that made Apple milk & tea (1 and 2), this is the successor of it. There's an English wiki page at http://defeatedcrow.jp/modwiki/HeatAndClimate_EN the documentation in english is a little sparse but it should be enough to get into it. Like Apple Milk & Tea, it adds a tremendous amount of food, which was my initial draw to it.  He has expanded it out from just food and now it some part a tech mod too. The basic premise of it is that there are three attributes added to the world: heat, humidity, and airflow that govern all the new recipes and mechanics added.

**Comment by WesCook** [comment]
Thanks for the explanation.  The Japanese mod scene is often underrepresented in modpacks, so I'm glad to offer support where possible.

I've gone ahead and merged in your changes and started testing them.  I noticed that a few foods don't actually yield any nutritional value for some reason, but I'd need to dig into the original source code to figure out why.  Most seem to work just fine though.

Cheers, nice work.

**Comment by WesCook** [comment]
These changes are included in [v2.9.0](https://github.com/WesCook/Nutrition/releases/tag/v2.9.0).

**Pull request merged**
