### PR TITLE
Add support for Bewitchment and Oh The Biomes You'll Go

### PR DESCRIPTION
**Pull request by vizthex123**
Based on my suggestion way back from #222.

### CODE REVIEW

**Comment by WesCook** [comment]
Thank you for the contribution.  I'll include this with the next release.

**Comment by vizthex123** [comment]
noice, thanks for accepting it. You know how I can avoid having to make 4 PRs next time? (since it was quite irksome to merge them all)

**Comment by WesCook** [comment]
Typically you'd fork the repo, checkout the branch locally, edit the files, then submit them under one commit.

If you're not familiar with git's workflow however, this can be difficult to learn.

**Comment by vizthex123** [comment]
yeah, I'm not lol. But thanks, guess I'll check out the docs next time.

**Pull request merged**
