### PR TITLE
Add additional foods to default configs

### PR DESCRIPTION
**Pull request by KnightMiner**
Added foods from:
* Biomes O Plenty
* Forestry
* Natura
* Roots
* Simply Tea
* Tinkers Construct

Updated foods from:
* Better With Mods

----

A few notes on the additions:
* I was not sure where to put honey, but other additions made me assume protein
* I decided to go with dairy for slime, both because the slight limitation in dairy options and it kinda makes sense (blood I put in protein instead though)
* I was not sure where to put tea, so I went with vegetable
* I added some .gitignores for eclipse stuff, not technically related to this PR so I can remove them if preferred.

### CODE REVIEW

**Comment by WesCook** [comment]
Looks great, thanks!

Honey, sugar, and candies I mostly just omitted as "empty calories".  Sometimes they just fall too far outside of the standard food groups to make sense.

Agreed on dairy being under-represented.  It was especially problematic with just vanilla foods, as cake is really the only dairy food in the game (as milk doesn't add any hunger).

**Comment by KnightMiner** [comment]
Would there be any way to special case (hard code) milk to be nutritious? Like set it up so if milk is detected it gets nutrients even without being a food?

**Comment by WesCook** [comment]
I considered doing so, but there's two problems:

1. Special casing is tricky when the nutrient system is meant to be completely modular.  "Dairy" might not even exist in another pack.
2. The hunger drain is used in balancing, as without it you could simply drink milk over and over again to maximize that stat.

So even if it were added, it would largely boil down to players having to stand beside a cow and drink from a bucket every once in a while.  I doubt the player would enjoy it (although the cow might).

I expect most players would be including other food mods with Nutrition, but for otherwise vanilla players they'd probably be better off just disabling Dairy.

**Comment by KnightMiner** [comment]
Would it be possible for Nutrition to add its own milk bottle item which restores a bit of hunger? Still not ideal for a vanilla foods only playthrough, bit it makes up for the lack of milk buckets in a standard one (as I am basically limited to slime and scrambled eggs right now)

Probably slightly off topic but his point, I can move discussion of this to a separate issue if desired.

**Comment by WesCook** [comment]
>Would it be possible for Nutrition to add its own milk bottle item which restores a bit of hunger?

That's a good suggestion.

Admittedly I am hesitant to add items, as I wanted Nutrition to be more of a complimentary mod than a "content mod".  This makes it easier to drop into packs, and keeps things less "opinionated" overall.

But I agree Dairy is a problem, so I'll give it some thought.

>as I am basically limited to slime and scrambled eggs right now

Just out of curiosity, what's your main hesitation to adding other food mods?  Is it that some mods like Harvestcraft can be "overkill"?  Or do you just have a more focused modpack in mind?

Unfortunately a lot of the smaller food mods haven't been ported to 1.11 yet.  There's some additional mod support on the 1.10 branch though.

Also, an interesting side note: the mod technically works with vanilla clients right now.  There's no GUI or tooltips, but player's nutrition will still be tracked and effects applied.  It's admittedly more of a novelty than anything, but it's a useful consequence of not adding any items or blocks.

**Comment by KnightMiner** [comment]
> Is it that some mods like Harvestcraft can be "overkill"? Or do you just have a more focused modpack in mind?

Mainly that. I have quite a few mods that add food without being just about food (good example is Forestry), and those foods get overshadowed when a giant food mod is added to the point I never end up using those foods. Plus, I am not entirely fond of the amount of microcrafting required just to get some foods in Harvestcraft (might have changed, but I recall in 1.7 the amount of steps to get some foods was extreme)

> It's admittedly more of a novelty than anything, but it's a useful consequence of not adding any items or blocks.

You could always tie it behind a config just so the mod still functions on vanilla clients if the user desires. You might be able to look into the vanilla scoreboard to make up for a lack of a GUI as well.

**Pull request merged**
