### PR TITLE
Begun fixing up lycanites support

### PR DESCRIPTION
**Pull request by Sunconure11**
This is a two man job. Requesting a bit of assistance to put this up to date.

### CODE REVIEW

**Comment by WesCook** [comment]
I imagine it'll mostly be meats.  Are you using the built-in logging features to produce a list of foods without nutrients?

**Comment by Sunconure11** [comment]
I'm searching through creative. But yeaaaah, I need a bit of aid here. Mostly because of how the internals of lycanites changed.

**Comment by WesCook** [comment]
Definitely turn on the two logging features.  It will expose a list of foods missing nutrients, and any foods that have nutrients assigned that don't (or no longer) exist.

I plan to do a final big cleanup to polish off the 1.12 version before moving it to maintenance mode.  It'll be good to get all these mods squared away.

It won't be easy to collaborate on this one at the same time, but you can submit half a PR if you'd like and I'll finish it off.

**Comment by Sunconure11** [comment]
Alright, should be ready for you to do then. I also added the start of support for this mod:

https://www.curseforge.com/minecraft/mc-mods/beasts

**Comment by WesCook** [comment]
I may nix that as it has only a few thousand downloads.  The goal isn't necessarily to support *everything*, because that adds a high maintenance burden.  I'll take a look at the mod and see how easy it will be to support.

**Pull request merged**
