### PR TITLE
Added support for various mods

### PR DESCRIPTION
**Pull request by Sunconure11**
1. Plants by Shadows_of_Fire
2. Rustic
3. Ice and Fire by Alexthe666
4. Aether Legacy
5. Aquaculture

**To do after I can get back in game (chisel issue, this will be handled as a separate pull):**

1. Floricraft

May or may not add support for crops from my own mod once it gets its first release

### CODE REVIEW

**Comment by KnightMiner** [comment]
The lists were typically sorted alphabetically to make it harder to accidently add duplicates

**Comment by Sunconure11** [comment]
Sorry, I'll fix that.

**Comment by Sunconure11** [comment]
Alright, I think I got it.

**Comment by WesCook** [comment]
Hey, thanks for the pull request.

Could you test if Aquaculture support is functional?  I had added support for that mod originally, but found that they added food values in a non-standard way which couldn't be detected easily.

**Comment by Sunconure11** [comment]
I'll test it tomorrow, I'll create a workspace that has this mod and aquaculture in it. You could talk to the dev of Aquaculture about this. You can currently find him on IRC as of typing this, under Glassmaker_

Check the Espernet IRC Server to find him.

**Comment by KnightMiner** [comment]
It might be easier to just load up a standard world with the two mods and copy these changes to the config when loading, as then you don't have to worry about deobfuscation and alike.

**Comment by Sunconure11** [comment]
screenshot 2017-06-16 22 23 20

Yeah, you might want to talk to @Glassmaker

**Comment by Sunconure11** [comment]
I got Glassmaker to look into it.

**Comment by WesCook** [comment]
All looks good here.  Thanks again!

I'll not add Aquaculture to the supported mods list until his next release, but will still merge it in for now.

**Comment by Sunconure11** [comment]
Aquaculture got updated.

**Pull request merged**
