### PR TITLE
Added support for XL Food Mod (except cakes)

### PR DESCRIPTION
**Pull request by ellor1138**
You can find the Google sheet/chart here : https://docs.google.com/spreadsheets/d/1dBPvdVuTaNiLzsbsHqRswyNYyHMpCGSD684vHaWVYII/edit?usp=sharing

### CODE REVIEW

**Comment by WesCook** [comment]
Looks great, thanks.

Were cakes not compatible?  It looks like they do extend BlockCake, so in theory should work fine.

https://github.com/mariot7/XL-Food-Mod/blob/1.12.2/src/main/java/mariot7/xlfoodmod/blocks/ChocolateCake.java#L20

**Comment by ellor1138** [comment]
I tried but the nutrients never showed up in JEI. I will have another go at it tomorrow just to be sure.

**Comment by WesCook** [comment]
You'll need to add IDs for both the block form, and item form.  That might have been the issue.

Sometimes they're the same (like `minecraft:cake`), but not always.

**Comment by ellor1138** [comment]
Can't seems to make it work.

I checked the log and here's what I've found. Minecraft cake and XL Food Mod cakes are not the same.

minecraft:cake Block{minecraft:cake}
minecraft:cake net.minecraft.item.**ItemBlockSpecial**@1ca0aa40

xlfoodmod:chocolate_cake is not a valid food (xlfoodmod:chocolate_cake)
xlfoodmod:chocolate_cake Block{xlfoodmod:chocolate_cake}
xlfoodmod:chocolate_cake net.minecraft.item.**ItemBlock**@46b3d095

image

**Comment by WesCook** [comment]
No sweat, thanks for investigating.  I'll merge it in now and take a quick look later as well.

I know Nutrition does check for both `ItemBlock` and `ItemBlockSpecial` when looking at cakes, but frankly that's some of the hackiest detection code in the mod so I wouldn't be surprised if something were off.

Thanks again for the contribution.

**Comment by WesCook** [comment]
Well sure enough.

image

Got me as to why it's not considered a cake, but we'll make do.

**Pull request merged**
