### PR TITLE
pyrotech support

### PR DESCRIPTION
**Pull request by WarlordWossman**

### CODE REVIEW

**Comment by WesCook** [comment]
Looks like a good contribution, thanks!  Is it ready to merge?

**Comment by WarlordWossman** [comment]
Those are all normal foods in pyrotech, one small thing I just came across now (because I got diary disabled in my modpacks) are the 3 buckets (wood, stone and clay) that can hold milk. Let me quickly enable diary and test if I can get those to work as well.

**Comment by WarlordWossman** [comment]
Hm, can't get those to work right now, they do store durability in their nbt, I thought not having any tag might work for all nbt data but doesn't appear to be the case.
You can merge this and look at the milk buckets yourself if you feel like it.

**Comment by WesCook** [comment]
I'd have guessed it would work, too.  NBT should be ignored, so only item ID + meta are checked.

Thanks for submitting these.  Merging now.

**Pull request merged**
