### PR TITLE
Defiled lands support

### PR DESCRIPTION
**Pull request by Sunconure11**
Trivial, but decided to add it anyways

### CODE REVIEW

**Comment by WesCook** [comment]
Could you explain the Plants update?  As I understand, the entries you changed are from Plants 1 (`Plants-1.12-1.2.0.jar`), which is still compatible with Minecraft 1.12.  Plants 2 (`Plants-2.0.2.jar`) should already be supported as of Nutrition v2.4.0.

The current configs should support both mods already.

**Comment by Sunconure11** [comment]
Plants changed its internal name, and also got a makeover in general.

**Comment by WesCook** [comment]
Yes, but were Plants 1 and Plants 2 both not already supported by the configs?

**Comment by Sunconure11** [comment]
They were supported, yes, via oredict definitions and what not. However, the internal names between versions, as mentioned before, changed. I can add back the old definitions if you wish, so that both are supported via configs.

**Comment by WesCook** [comment]
I've had a chance to review the file changes more closely.  I'd like to clear up any confusion between on this topic, if possible.

First, I'd like to clarify that I'm using "Plants 1" to refer to the old version of the mod, and "Plants 2" to refer to the new version.  While the name is still just "Plants" on the Curseforge page, the modid and version numbers have changed.

Secondly, the reason I wanted to support both was because both were still released for Minecraft 1.12.  While I'm sure we could drop support for Plants 1 eventually as it falls out of favor, it seemed premature to do so already.

What I've not understood is why any changes were needed in the first place, as from what I could tell both mods were already completely supported.  Their support wasn't inherited from oredicts.  All food items have been listed in the configs.

Your changes seemed to be updating the modid `plants` to `plants2` in each file, and then after we spoke you added back the original `plants` entries as well.  However, as Plants 2 support had already been added, this has created duplicate entries.  For instance `plants2:okra` now exists twice under `vegetable.json`.

Does this make sense?  Hopefully we can be on the same page about these changes now.

**Comment by Sunconure11** [comment]
I added the entries from both plants 1 and 2 for the items, as to add support for both, I don't see an actual duplicate. Could you point me to the line the duplicate is on, so I can fix it?

**Comment by Sunconure11** [comment]
Fuck, I see them. I'll go on my pc and deal with them.

**Comment by WesCook** [comment]
I gave an example in my previous comment.  There are two instances of plants2:okra under vegetable.json.

https://github.com/Sunconure11/Nutrition/blob/feb508e6ecebb94cc51d9c0a2893006dc9ea3d4f/src/main/resources/assets/nutrition/configs/nutrients/vegetable.json#L338,L350

However to be more clear, I'd ask that Plants not be modified at all unless there's a specific fix that needs to be made.  In such a case it would be best to create a dedicated PR for that, and with a clear explanation behind the intention of the fix.

Currently Plants 1 and 2 support are working as intended.  The modid does not need to be updated, and so the issue the original commits were intended to solve are not needed.  I'd ask that the Plants-related changes be removed from this PR.

**Comment by Sunconure11** [comment]
I'll create a commit with better support at another time, I'm going to revert the changes. I did not even realize I accidentally created duplicates.

**Comment by Sunconure11** [comment]
Fixed.

**Pull request merged**
