### PR TITLE
Start of Primal Core support

### PR DESCRIPTION
**Pull request by Sunconure11**
This mod is organized very weirdly, I think I need some more aid for this. I will work on this with what little time I have left before I am away from 6 days.

### CODE REVIEW

**Comment by Sunconure11** [comment]
Will attempt to continue on 8/6/17

**Comment by WesCook** [comment]
Looks like a complex one.  I'll leave this for now until you consider it complete.

Have the improved logging tools helped in adding support for new mods?  I wanted to make that process easier.

**Comment by Sunconure11** [comment]
I just use crafttweaker in picking up support.

**Comment by Sunconure11** [comment]
Merge this now, I'll finish up support once the move shenanigans are dealt with. Plus this is one tough mod to add support for. Should meats that apply the hunger debuff be given support, for instance?

**Comment by Sunconure11** [comment]
I have access to a machine now. However, I will continue this later this week.

**Comment by Sunconure11** [comment]
Eh, I think I might be too busy to continue this, would it be possible to merge this, and add the rest of the support for it? Because its... big.

**Comment by WesCook** [comment]
Sorry for the delay on this - I had some other projects on the go.

I've finished support for this mod in [v2.3.0](https://github.com/WesCook/Nutrition/releases/tag/v2.3.0).

**Pull request merged**
